name: Check Installation with p2 site

on:
  pull_request:
    paths-ignore:
     - '**.md'

jobs:
  build:
    strategy:
      matrix:
        eclipse-version: ['2022-06', 'oxygen']
      fail-fast: false
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        # Shallow clones should be disabled for a better relevancy of SonarQube analysis
        fetch-depth: 0
    - name: Set up JDK 17
      uses: actions/setup-java@v3.6.0
      with:
        java-version: 17
        distribution: temurin
    - name: Set up Maven
      uses: stCarolas/setup-maven@v5
      with:
        maven-version: 3.9.6
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: |
          ~/.m2
        key: ${{ runner.os }}-p2-${{ hashFiles('**/pom.xml', '**/*.yml', '**/*.target') }}
        restore-keys: ${{ runner.os }}-p2-
    - name: Verify Installation
      run: >
         mvn verify -Pverify-installation -Dmaven.test.skip=true -Declipse-version=${{ matrix.eclipse-version }}
    - name: Show installed contents
      run: tree /home/runner/work/pitclipse/pitclipse/releng/org.pitest.pitclipse.p2/target/installed-plugins
