# It builds using an old Eclipse TP

name: Java CI with Maven Old TP

on:
  push:
    paths-ignore:
     - '**.md'
  pull_request:
    paths-ignore:
     - '**.md'

jobs:
  build:
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        # Shallow clones should be disabled for a better relevancy of SonarQube analysis
        fetch-depth: 0
    - name: Set up JDK 17
      uses: actions/setup-java@v3.6.0
      with:
        java-version: 17
        distribution: temurin
    - name: Set up Maven
      uses: stCarolas/setup-maven@v5
      with:
        maven-version: 3.9.6
    - name: Install WebKit # required for SWT Browser
      run: |
        sudo apt update
        sudo apt install -y libwebkit2gtk-4.0-37
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: |
          ~/.m2
          ~/.sonar/cache
        key: ${{ runner.os }}-oldtp-m2-${{ hashFiles('**/pom.xml', '**/*.yml', '**/*.target') }}
        restore-keys: ${{ runner.os }}-oldtp-m2-
    - name: Maven Build
      run: >
         xvfb-run mvn verify -Dtarget-file-name=older.target
    - name: Archive Test Results
      uses: actions/upload-artifact@v2
      if: ${{ failure() || cancelled() }}
      with:
        name: test-results-${{ runner.os }}
        path: '**/*.tests/target'
    - name: Archive UI Tests Screenshots
      uses: actions/upload-artifact@v2
      if: ${{ failure() || cancelled() }}
      with:
        name: screenshots-${{ runner.os }}
        path: '**/*.tests/screenshots'
